
#pragma once

#include <X11/Xlib.h>
#include <X11/keysym.h>

namespace zephyr::input {
    
    enum class Key : KeySym {
        Space = XK_space,
        Apostrophe = XK_apostrophe,
        Comma = XK_comma,
        Minus = XK_minus,
        Period = XK_period,
        Slash = XK_slash,
        Num0 = XK_0,
        Num1 = XK_1,
        Num2 = XK_2,
        Num3 = XK_3,
        Num4 = XK_4,
        Num5 = XK_5,
        Num6 = XK_6,
        Num7 = XK_7,
        Num8 = XK_8,
        Num9 = XK_9,
        Semicolon = XK_semicolon,
        Equal = XK_equal,
        A = XK_a,
        B = XK_b,
        C = XK_c,
        D = XK_d,
        E = XK_e,
        F = XK_f,
        G = XK_g,
        H = XK_h,
        I = XK_i,
        J = XK_j,
        K = XK_k,
        L = XK_l,
        M = XK_m,
        N = XK_n,
        O = XK_o,
        P = XK_p,
        Q = XK_q,
        R = XK_r,
        S = XK_s,
        T = XK_t,
        U = XK_u,
        V = XK_v,
        W = XK_w,
        X = XK_x,
        Y = XK_y,
        Z = XK_z,
        LeftBracket = XK_bracketleft,
        Backslash = XK_backslash,
        RightBracket = XK_bracketright,
        GraveAccent = XK_grave,
        World1 = XK_dead_grave,
        World2 = XK_dead_acute,
        Escape = XK_Escape,
        Enter = XK_Return,
        Tab = XK_Tab,
        Backspace = XK_BackSpace,
        Insert = XK_Insert,
        Delete = XK_Delete,
        Right = XK_Right,
        Left = XK_Left,
        Down = XK_Down,
        Up = XK_Up,
        PageUp = XK_Page_Up,
        PageDown = XK_Page_Down,
        Home = XK_Home,
        End = XK_End,
        CapsLock = XK_Caps_Lock,
        ScrollLock = XK_Scroll_Lock,
        NumLock = XK_Num_Lock,
        PrintScreen = XK_Print,
        Pause = XK_Pause,
        F1 = XK_F1,
        F2 = XK_F2,
        F3 = XK_F3,
        F4 = XK_F4,
        F5 = XK_F5,
        F6 = XK_F6,
        F7 = XK_F7,
        F8 = XK_F8,
        F9 = XK_F9,
        F10 = XK_F10,
        F11 = XK_F11,
        F12 = XK_F12,
        F13 = XK_F13,
        F14 = XK_F14,
        F15 = XK_F15,
        F16 = XK_F16,
        F17 = XK_F17,
        F18 = XK_F18,
        F19 = XK_F19,
        F20 = XK_F20,
        F21 = XK_F21,
        F22 = XK_F22,
        F23 = XK_F23,
        F24 = XK_F24,
        F25 = XK_F25,
        Numpad0 = XK_KP_0,
        Numpad1 = XK_KP_1,
        Numpad2 = XK_KP_2,
        Numpad3 = XK_KP_3,
        Numpad4 = XK_KP_4,
        Numpad5 = XK_KP_5,
        Numpad6 = XK_KP_6,
        Numpad7 = XK_KP_7,
        Numpad8 = XK_KP_8,
        Numpad9 = XK_KP_9,
        NumpadDecimal = XK_KP_Decimal,
        NumpadDivide = XK_KP_Divide,
        NumpadMultiply = XK_KP_Multiply,
        NumpadSubtract = XK_KP_Subtract,
        NumpadAdd = XK_KP_Add,
        NumpadEnter = XK_KP_Enter,
        NumpadEqual = XK_KP_Equal,
        LeftShift = XK_Shift_L,
        LeftControl = XK_Control_L,
        LeftAlt = XK_Alt_L,
        LeftSuper = XK_Super_L,
        RightShift = XK_Shift_R,
        RightControl = XK_Control_R,
        RightAlt = XK_Alt_R,
        RightSuper = XK_Super_R,
        Menu = XK_Menu
    };

    namespace underground {
        extern Display *display;
    }

    bool isKeyPressed(const Key key);
    bool isKeyReleased(const Key key);

} // namespace zephyr::input
